# Generated by Django 4.2.1 on 2023-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('police', 'Police Station'), ('analytics', 'Analytics Team'), ('admin', 'Admin')], default='police', max_length=10),
            preserve_default=False,
        ),
    ]
