# Generated by Django 4.2.1 on 2023-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_validationemailcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationemailcodes',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
    ]
