# Generated by Django 4.2.1 on 2023-06-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_validationemailcodes_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
