# Generated by Django 4.2.1 on 2023-07-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_approvalrequests_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequests',
            name='work_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
